### ISSUE TITLE
Problem running denoise

### ISSUE THREAD

**Issue by manzouri** [arielletambini/denoiser#35]
Hi, 
I am trying to run denoise on my data but getting the following error: 
Command: 
    'python run_denoise.py /home/data/OUT/derivatives/fmriprep/sub-101/ses-01/func/sub-101_ses-01_task-touch_run-1_space-MNI152NLin2009cAsym_desc-preproc_bold.nii.gz /home/data/OUT/derivatives/fmriprep/sub-101/ses-01/func/sub-101_ses-01_task-touch_run-1_desc-confounds_timeseries.tsv /home/data/OUT/derivatives/fmriprep/sub-101/ses-01/func/ --col_names csf white_matter framewise_displacement --hp_filter 0.01'

Output:
/home/amiman/anaconda3/lib/python3.7/site-packages/nilearn/glm/__init__.py:56: FutureWarning: The nilearn.glm module is experimental. It may change in any future release of Nilearn.
  'It may change in any future release of Nilearn.', FutureWarning)
/home/amiman/anaconda3/lib/python3.7/site-packages/sklearn/feature_extraction/text.py:17: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  from collections import Mapping, defaultdict
# of TRs: 296
Filling in 1 NaN value for framewise_displacement
# of Confound Regressors: 3  [SELECTED regressors in CSV]
# of High-pass Filter Regressors: 9
Saving output file...
Output directory: /home/data/OUT/derivatives/fmriprep/sub-101/ses-01/func/sub-101_ses-01_task-touch_run-1_space-MNI152NLin2009cAsym_desc-preproc_bold_NR_figures
FD not found: FD timeseries not plotted
Computing dvars...
Traceback (most recent call last):
  File "run_denoise.py", line 463, in <module>
    denoise(img_file, tsv_file, out_path, col_names, hp_filter, lp_filter, out_figure_path)
  File "run_denoise.py", line 376, in denoise
    del fig, ax0, ax_curr, ax_d, dvars
UnboundLocalError: local variable 'ax0' referenced before assignment

**Comment by arielletambini** [comment]
I also obtained a similar error (due to the 'framewise_displacement' field not being listed as an option for the FD column name), and modified the code yesterday to fix this. Could you pull the updated version and see if this fixes the error? Alternatively, what is the name of the framewise displacement column in the .tsv file that you are using?

**Comment by manzouri** [comment]
Hi and thanks . I will try it . The name is "framewise_displacement" in the .tsv file.

**Comment by manzouri** [comment]
Hi again, Now it runs without error and I get the output file but not the output html. IS there anything I missed?
