### ISSUE TITLE
RuntimeWarning: Divide by zero 

### ISSUE THREAD

**Issue by manzouri** [arielletambini/denoiser#42]
Hi , I run the denoiser and get the output file but not the html report due to the following error:

Computing dvars...
/home/amir/.local/lib/python3.8/site-packages/numpy/lib/shape_base.py:379: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  res = asanyarray(func1d(inarr_view[ind0], *args, **kwargs))
/home/amir/.local/lib/python3.8/site-packages/numpy/lib/shape_base.py:402: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  buff[ind] = asanyarray(func1d(inarr_view[ind], *args, **kwargs))
Traceback (most recent call last):
  File "run_denoise.py", line 462, in <module>
    denoise(img_file, tsv_file, out_path, col_names, hp_filter, lp_filter, out_figure_path)
  File "run_denoise.py", line 316, in denoise
    temp = nac.compute_dvars(in_file=in_file, in_mask=mask_file)[1]
  File "/home/amir/.local/lib/python3.8/site-packages/nipype/algorithms/confounds.py", line 1079, in compute_dvars
    func_diff / np.array([diff_sdhat] * func_diff.shape[-1]).T
RuntimeWarning: divide by zero encountered in true_divide

**Comment by maxhenneke** [comment]
I am getting this same error. Did you end up finding a solution?

**Comment by manzouri** [comment]
@maxhenneke , Unfortunately No. I was hoping for an update from @arielletambini
